import type { Metadata } from "next";
import { Urbanist, Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Load fonts using next/font/google
const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-urbanist",
  display: "swap",
});

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-figtree",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "meraj-netzet-job-task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${urbanist.variable}
          ${figtree.variable}
          ${geistSans.variable}
          ${geistMono.variable}
          font-sans antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
